export {MaterialUISwitch,IOSSwitch,AntSwitch,Android12Switch} from "./component/Switch"
export {Logo} from "./component/Logo"
export {Loader} from "./Loader"
export {default as Header} from "./Header"
export {default as Footer} from "./Footer"