export {setTheme,switchTheme,switchSelectPair,GetCurrentCurrency,GetCurrentPrices,GetBuySellFark} from "./siteController"
export {resetMarket} from "./marketController"
export {resetOrder} from "./orderController"
export {PHONE_REGEX, PASSWORD_REGEX} from "./formController"
export {default as Translate} from "./translate"